sonar.projectKey=task-manager
sonar.projectName=TaskFlow - Task Manager
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=src/public/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/public/**,tests/**

sonar.sourceEncoding=UTF-8